name: Terraform Deploy

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::417556509510:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (PR only)
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply (Main branch only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
