name: Terraform Plan then Apply (Approve)

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    outputs:
      plan_status: ${{ steps.plan.outputs.status }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::417556509510:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: |
          set +e
          terraform plan -no-color -input=false -detailed-exitcode -out=tfplan
          EXITCODE=$?

          if [ $EXITCODE -eq 1 ]; then
            echo "Terraform plan failed."
            exit 1
          fi

          if [ $EXITCODE -eq 2 ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest

    # Only run if plan succeeded
    if: ${{ needs.plan.result == 'success' }}

    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::417556509510:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false tfplan